export const adminCopy = {
  title: "Admin",
  signInTitle: "Sign in to Admin",
  signInBody: "Use the operator account created with the bootstrap command.",
  email: "Email",
  password: "Password",
  signIn: "Sign in",
  signInError: "Could not sign in.",
  signOut: "Sign out",
  topics: "Topics",
  conversations: "Conversations",
  newTopic: "New topic",
  saveDraft: "Save draft",
  publish: "Publish",
  unpublish: "Unpublish",
  preview: "Preview",
  backToEdit: "Back to edit",
  backToTopics: "All topics",
  topicsListHint: "This order is the public landing order. Open a topic to edit, preview, and publish.",
  unsaved: "Unsaved",
  statusDraftWaiting: "draft waiting",
  previewCard: "Landing card",
  previewWorkspace: "Workspace",
  english: "English",
  bangla: "Bangla",
  slug: "Slug",
  slugLocked: "Slug is locked after first publication.",
  theme: "Theme",
  themeTax: "Tax",
  themeLiterature: "Literature",
  themeHistory: "History",
  themeCulture: "Culture",
  focalPosition: "Artwork crop",
  focalPositionHint: "Which part of the image stays visible on the landing card.",
  knowledgeReviewDate: "Knowledge review date",
  artwork: "Artwork",
  artworkHint: "Shown on the public landing card and workspace. Upload or reuse an existing image.",
  artworkPreview: "Artwork preview",
  artworkOpenPreview: "View larger",
  closeArtworkPreview: "Close artwork preview",
  artworkUploading: "Uploading…",
  artworkUploaded: "Artwork selected. Save the draft to keep it on this topic.",
  uploadArtwork: "Upload image",
  apeProject: "Knowledge project",
  apeProjectHint:
    "Stored on this topic in the database. Choose a listed project or paste its UUID, then save the draft. Publish to use it for answers.",
  apeProjectPlaceholder: "APE project UUID",
  apeProjectChoose: "Choose a knowledge project",
  apeProjectSaved: "Knowledge project selected. Save the draft to keep it on this topic.",
  apeProjectListUnavailable:
    "APE project list could not be loaded. Paste a UUID and save the draft.",
  apeProjectClear: "Clear knowledge project",
  apeProjectLiveDiffers:
    "This draft uses a different project than the live topic. Publish to switch answers.",
  checkProject: "Check project",
  loadMoreProjects: "Load more projects",
  titleField: "Title",
  landingDescription: "Landing description",
  workspaceSubtitle: "Workspace subtitle",
  aboutDescription: "About this topic",
  sourceDescription: "Source description",
  artworkAlt: "Artwork alt text",
  composerPlaceholder: "Composer placeholder",
  badge: "Badge",
  exploreLabel: "Explore label",
  starterQuestions: "Starter questions",
  starterQuestionsHint: "One question per line. Publish requires 1–10 English questions.",
  previewYouLabel: "Example “you” label",
  previewAssistantLabel: "Example assistant label",
  previewQuestion: "Example question",
  previewAnswer: "Example answer",
  previewSources: "Example source labels",
  previewHint: "Leave all example fields empty to omit the card preview. Save them together as one example.",
  previousPage: "Previous",
  nextPage: "Next",
  statusDraft: "Draft",
  statusLive: "Live",
  statusUnpublished: "Unpublished",
  emptyTopics: "No topics yet. Create one to start.",
  emptyConversations: "No conversations yet.",
  filterTopic: "All topics",
  conversationState: "State",
  created: "Created",
  lastActivity: "Last activity",
  transcriptUnavailable: "The transcript could not be loaded from APE.",
  transcriptMissing: "APE has not stored a conversation for this reference yet.",
  feedbackUp: "Helpful",
  feedbackDown: "Not helpful",
  moveUp: "Move up",
  moveDown: "Move down",
  conflict: "This topic was changed by another edit. Your text is still here.",
  conflictKeepMine: "Keep my text and retry",
  conflictRestoreStored: "Restore stored draft",
  conflictVersionReady: "Loaded the current version. Review your text and save again.",
  conflictRestored: "Restored the stored draft.",
  conflictSlugReconciled: "Slug is locked to the published value. Your other text is still here.",
  networkError: "The request did not finish. Your text is still here — try again.",
  uncertainSave: "The last save may not have completed. Version refreshed — review and save again.",
  saveBeforePublish: "Save the draft before publishing. Preview can show unsaved text; publish uses the last saved revision.",
  previewUnsaved: "Preview shows unsaved fields. Publish uses the last saved revision.",
  clearArtwork: "Clear artwork",
  existingArtwork: "Choose artwork",
  artworkNone: "None (gradient)",
  slugHint: "Lowercase letters, numbers, and hyphens. Locked after first publish.",
  loadMoreMessages: "Load earlier messages",
  transcriptTruncated: "Stopped after the inspection limit. Open APE if you need the rest.",
  transcriptPageFailed: "Could not load more of the transcript.",
} as const;
